# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auth < Formula
  desc ""
  homepage "https://formance.com"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/auth/releases/download/v0.3.1/auth_darwin-arm64.tar.gz"
      sha256 "2267361acbb5fe36d1a709fb3f2defda70497b8240920f6b97abebbced9d68a5"

      def install
        bin.install "auth"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/auth/releases/download/v0.3.1/auth_darwin-amd64.tar.gz"
      sha256 "41472dc359da0b4edfbb36a5c123e1acb4bd17784b3fe13b0157ed500a27c3f2"

      def install
        bin.install "auth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/auth/releases/download/v0.3.1/auth_linux-arm64.tar.gz"
      sha256 "d36b25b1c4533abdd3404b87ae12734c5d95a30c5c689ab24b17c2a160576144"

      def install
        bin.install "auth"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/auth/releases/download/v0.3.1/auth_linux-amd64.tar.gz"
      sha256 "a2e0e42225ae35a5af8cd420fe7687edcd4dd06dd8cccafcde7d4b43f70e43f0"

      def install
        bin.install "auth"
      end
    end
  end

  test do
    system "#{bin}/auth version"
  end
end
