# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FctlAT3 < Formula
  desc ""
  homepage "https://formance.com"
  version "3.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/fctl/releases/download/v3.0.1/fctl_darwin-amd64.tar.gz"
      sha256 "adccf63868fa5e8116492d28ac4415451d4a9d4b1b436e1622e7c156901710a6"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/fctl/releases/download/v3.0.1/fctl_darwin-arm64.tar.gz"
      sha256 "760b3da5c0e0167035224885e70b115cdd337662cfd811438e48c7e0f2cb17de"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.0.1/fctl_linux-amd64.tar.gz"
      sha256 "5695cb2adaa497a644e75bf49e2200388814df86a277859144a439fbbf98131f"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.0.1/fctl_linux-arm64.tar.gz"
      sha256 "787781bf89e512213b33a1260ded7d5a2987ae349dca5cba24251961ae75b182"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
