# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FctlAT2 < Formula
  desc ""
  homepage "https://formance.com"
  version "2.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/fctl/releases/download/v2.6.0/fctl_darwin-amd64.tar.gz"
      sha256 "ced3c624bea09b10af396c8157aa231aa727a53d90d10a1ceac57edc8f805628"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/fctl/releases/download/v2.6.0/fctl_darwin-arm64.tar.gz"
      sha256 "47e0786ab2f0430403c13233edf3cef41e5acf39d792e3a31d9b96288aae0aef"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v2.6.0/fctl_linux-amd64.tar.gz"
      sha256 "a838108952c1b80f035614f67114c059455c6a2a5bd73dfd0fb767eab7daf417"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v2.6.0/fctl_linux-arm64.tar.gz"
      sha256 "caa84dff428e4c62635192731a76d56f3ce3e77008e03c0145a6a1c52badd313"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
