# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fctl < Formula
  desc ""
  homepage "https://formance.com"
  version "0.11.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/stack/releases/download/components/fctl/v0.11.3/fctl_darwin-arm64.tar.gz"
      sha256 "411ae1a1c461d6cc8445431cd5a14c91d4156f7da22c059cfb0120512da8b191"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/stack/releases/download/components/fctl/v0.11.3/fctl_darwin-amd64.tar.gz"
      sha256 "9ec3a865ec1a53be48b2daaa646753c097465ab64d81a50b623279a306714744"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/stack/releases/download/components/fctl/v0.11.3/fctl_linux-arm64.tar.gz"
      sha256 "473d2c1f952491795002be4b694cb4bc5a2d7bd2608384b7a8e9f05ea013a36d"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/stack/releases/download/components/fctl/v0.11.3/fctl_linux-amd64.tar.gz"
      sha256 "ae79c5bb1eb0837fb39e4a8219cc3a7386d3d49b9c1367e207a878ed26174beb"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
