# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fctl < Formula
  desc ""
  homepage "https://formance.com"
  version "3.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/fctl/releases/download/v3.2.0/fctl_darwin-amd64.tar.gz"
      sha256 "cf1758383aaaa447229ec876fb5159e4fff27285d57fd12f51191e12b97e2ffb"

      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/fctl/releases/download/v3.2.0/fctl_darwin-arm64.tar.gz"
      sha256 "54608e888bcf531ecd97c659930b5186e8c079eb27589bbce92dafd1cdfd9fc7"

      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.2.0/fctl_linux-amd64.tar.gz"
      sha256 "4ac2275fe16857bf24dcd5a9df89969c1a2ccb4ebd7ea3cdbf7e86dfb0c61c6d"
      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.2.0/fctl_linux-arm64.tar.gz"
      sha256 "54c61b9a6c63248b075dde18152b7eb3025c398447eb7f7547b6ad5d945838f0"
      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
