# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FctlAT3 < Formula
  desc ""
  homepage "https://formance.com"
  version "3.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/fctl/releases/download/v3.5.0/fctl_darwin-amd64.tar.gz"
      sha256 "99ce144afafafb6231f9d53bb0ff6b13ae694fa73ad98eaf02489769de3badf1"

      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/fctl/releases/download/v3.5.0/fctl_darwin-arm64.tar.gz"
      sha256 "19b4975f56ebee2f5c2f8c4594bd47cd2597da0b1dfca104ff0d4a914c13a29e"

      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.5.0/fctl_linux-amd64.tar.gz"
      sha256 "117fdc1f3a9baa129510b43d1bd6769243e86baa4219499705c2b259203b3ccb"
      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.5.0/fctl_linux-arm64.tar.gz"
      sha256 "1642768339de5eec187807a5f148f27a69a9bc4a75e88a62e00c59f14ba6fa8f"
      define_method(:install) do
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
