# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FctlAT2 < Formula
  desc ""
  homepage "https://formance.com"
  version "2.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/fctl/releases/download/v2.4.0/fctl_darwin-amd64.tar.gz"
      sha256 "f94ca37f52b2e12109860e31b28d6d30d91d92dde6f22c4832b6d7294f3d4c39"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/fctl/releases/download/v2.4.0/fctl_darwin-arm64.tar.gz"
      sha256 "4b41215fac46047716fcbcd42e60c7b12d6f9e761ebedb8f7bbe3e5b3d1c21fc"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v2.4.0/fctl_linux-amd64.tar.gz"
      sha256 "0a34856948b63af4fdd23efa2cacf937012647845e31c0d8f63d8280f41dddcb"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v2.4.0/fctl_linux-arm64.tar.gz"
      sha256 "cc267066cd5a2c52cf953f35de1055261568e0443668f9e679a2775a2ba450e8"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
