# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FctlAT3 < Formula
  desc ""
  homepage "https://formance.com"
  version "3.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/fctl/releases/download/v3.1.1/fctl_darwin-amd64.tar.gz"
      sha256 "83d4d4bfb2b64d7c447896b18301b70c111111d057f2b18a62f4c33db0135913"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/fctl/releases/download/v3.1.1/fctl_darwin-arm64.tar.gz"
      sha256 "c2b22b15974b9b143ee6b3a1831eb4f8741576852ec7ffe47d0cec33d12c924d"

      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.1.1/fctl_linux-amd64.tar.gz"
      sha256 "afecd89f32bb4d40b910799724e4534e5f12508b44dcbbccbf532c8b3e92c343"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/fctl/releases/download/v3.1.1/fctl_linux-arm64.tar.gz"
      sha256 "3299cdc34c5c8935ee9ba9a8feea4c210f3958e6dcfc61e9c97eae0db71262e8"
      def install
        bin.install "fctl"
        bash_completion.install "completions/fctl.bash" => "fctl"
        zsh_completion.install "completions/fctl.zsh" => "_fctl"
        fish_completion.install "completions/fctl.fish"
      end
    end
  end

  test do
    system "#{bin}/fctl version"
  end
end
