# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ledger < Formula
  desc ""
  homepage "https://formance.com"
  version "2.2.35"

  on_macos do
    on_intel do
      url "https://github.com/formancehq/ledger/releases/download/v2.2.35/ledger_darwin-amd64.tar.gz"
      sha256 "b7e4899ef5010fc843a8e08a4965eb93f0316edc225ec2282ed6abd9375fe130"

      def install
        bin.install "ledger"
      end
    end
    on_arm do
      url "https://github.com/formancehq/ledger/releases/download/v2.2.35/ledger_darwin-arm64.tar.gz"
      sha256 "60e3abb58e07f13eb5cea18a6dc1e34401fbcbcea4cf15c41ce7a690c6e65a32"

      def install
        bin.install "ledger"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/formancehq/ledger/releases/download/v2.2.35/ledger_linux-amd64.tar.gz"
        sha256 "72d2e264908fa57328e98df8cf17e5746a2dd17ac600a35962e10db9f6d3632f"

        def install
          bin.install "ledger"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/formancehq/ledger/releases/download/v2.2.35/ledger_linux-arm64.tar.gz"
        sha256 "3e25d0304f207f3eee0f6e734b5a2a8ed19d45d61adc1e7bd0b9fc88f35ec30c"

        def install
          bin.install "ledger"
        end
      end
    end
  end

  test do
    system "#{bin}/ledger version"
  end
end
