# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LedgerAT2 < Formula
  desc ""
  homepage "https://formance.com"
  version "2.2.31"

  on_macos do
    on_intel do
      url "https://github.com/formancehq/ledger/releases/download/v2.2.31/ledger_darwin-amd64.tar.gz"
      sha256 "909aa29e2c135bf97de1b3a9341871659fe37b97ec0923899229224a566a0932"

      def install
        bin.install "ledger"
      end
    end
    on_arm do
      url "https://github.com/formancehq/ledger/releases/download/v2.2.31/ledger_darwin-arm64.tar.gz"
      sha256 "c188e340deb0ec87fa0a4066994185588c16d1c0c773b97aef1110377dfde344"

      def install
        bin.install "ledger"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/formancehq/ledger/releases/download/v2.2.31/ledger_linux-amd64.tar.gz"
        sha256 "27ad222accf88eea7e8f51016a61e5ae379f74eb9fd43efa6d425c4bcd4a91d5"

        def install
          bin.install "ledger"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/formancehq/ledger/releases/download/v2.2.31/ledger_linux-arm64.tar.gz"
        sha256 "5da00b60b53f1f8cc4d60b2db3f836650e2b7f16f6663a0d2c2a0614b4671fa4"

        def install
          bin.install "ledger"
        end
      end
    end
  end

  test do
    system "#{bin}/ledger version"
  end
end
