# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LedgerAT2 < Formula
  desc ""
  homepage "https://formance.com"
  version "2.2.7"

  on_macos do
    on_intel do
      url "https://github.com/formancehq/ledger/releases/download/v2.2.7/ledger_darwin-amd64.tar.gz"
      sha256 "3207c2485e4e68e26d9e620722782e7218c6780871d919709b2ebba519bd5eb9"

      def install
        bin.install "ledger"
      end
    end
    on_arm do
      url "https://github.com/formancehq/ledger/releases/download/v2.2.7/ledger_darwin-arm64.tar.gz"
      sha256 "a8230391534d048431165476f419a500fc0f7f9b5e856b481b54790062a19b16"

      def install
        bin.install "ledger"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/formancehq/ledger/releases/download/v2.2.7/ledger_linux-amd64.tar.gz"
        sha256 "065227c2a136e2deb7119b8419eedc49250e1fc9bf2b86fb39cc9e5e7ef9afd5"

        def install
          bin.install "ledger"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/formancehq/ledger/releases/download/v2.2.7/ledger_linux-arm64.tar.gz"
        sha256 "38b67584a9e0f5000bcd0b13824a5985a13dd2d5fbd5077b061a252fdda72dc4"

        def install
          bin.install "ledger"
        end
      end
    end
  end

  test do
    system "#{bin}/ledger version"
  end
end
