# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ledger < Formula
  desc ""
  homepage "https://formance.com"
  version "2.4.0-beta.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/ledger/releases/download/v2.4.0-beta.3/ledger_darwin-amd64.tar.gz"
      sha256 "a8435983d261726e3f52d6a5fc0d449d5b703985438e06f845da8b7aa64ad175"

      def install
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/ledger/releases/download/v2.4.0-beta.3/ledger_darwin-arm64.tar.gz"
      sha256 "d653bfa5a2419783ed0a7bacaf476b27192d4d8130a60387f3ac8d3b975d8392"

      def install
        bin.install "ledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/ledger/releases/download/v2.4.0-beta.3/ledger_linux-amd64.tar.gz"
      sha256 "11bc00dd70ce5852f4f2e970734ef92505aa419a02b72206507f0e614af517c6"
      def install
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/ledger/releases/download/v2.4.0-beta.3/ledger_linux-arm64.tar.gz"
      sha256 "8c108a9e0e009bf3398de19d607b7d8c813a2a822015ffd94ffe470aac412de7"
      def install
        bin.install "ledger"
      end
    end
  end

  test do
    system "#{bin}/ledger version"
  end
end
