# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LedgerAT2 < Formula
  desc ""
  homepage "https://formance.com"
  version "2.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/ledger/releases/download/v2.3.2/ledger_darwin-amd64.tar.gz"
      sha256 "47de00583347656b59b4d5c2f56a1a8dff8dc4a29cabe3c533949213eadfa2e9"

      def install
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/ledger/releases/download/v2.3.2/ledger_darwin-arm64.tar.gz"
      sha256 "b3a1cbeec8a2eaccc5fc5d0222f385ee9b80333be075a78d927ae04457139b36"

      def install
        bin.install "ledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/ledger/releases/download/v2.3.2/ledger_linux-amd64.tar.gz"
      sha256 "8935c8f77da07bd652d52c30bb5fec99c8883973fff76db9cb59df1b66a8327c"
      def install
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/ledger/releases/download/v2.3.2/ledger_linux-arm64.tar.gz"
      sha256 "110efd5941f66ec62c54069302ddec48689da0434892d9ab6055142472ccf759"
      def install
        bin.install "ledger"
      end
    end
  end

  test do
    system "#{bin}/ledger version"
  end
end
