# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Numary < Formula
  desc ""
  homepage "https://numary.com"
  version "1.0.0-rc3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/numary/ledger/releases/download/v1.0.0-rc3/numary_1.0.0-rc3_macOS-ARM64.tar.gz"
      sha256 "9e716e8e3e22c6dd15df74b3db7334adeebe5e539a24ab7b108dd4866154caa0"

      def install
        bin.install "numary"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/numary/ledger/releases/download/v1.0.0-rc3/numary_1.0.0-rc3_macOS-64bit.tar.gz"
      sha256 "2595f13659cf6d48610ff55d1bd2051a1e9f863027cee16a3fa021789246a64e"

      def install
        bin.install "numary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/numary/ledger/releases/download/v1.0.0-rc3/numary_1.0.0-rc3_Linux-64bit.tar.gz"
      sha256 "8cb8315374aad87a791c36994c6c6f82b748cbecc4c613f678f5635d1fcf8d67"

      def install
        bin.install "numary"
      end
    end
  end

  test do
    system "#{bin}/numary version"
  end
end
