# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Numary < Formula
  desc ""
  homepage "https://numary.com"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/numary/ledger/releases/download/v1.1.0/numary_1.1.0_macOS-ARM64.tar.gz"
      sha256 "02c0db95916f9bd654207003cca04f5de09566ff17c9b68821ee1dcfd5891e5c"

      def install
        bin.install "numary"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/numary/ledger/releases/download/v1.1.0/numary_1.1.0_macOS-64bit.tar.gz"
      sha256 "6b14c3cf268c6aad45009399e940bd19204594628cf83502bbab1318be7d3eac"

      def install
        bin.install "numary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/numary/ledger/releases/download/v1.1.0/numary_1.1.0_Linux-64bit.tar.gz"
      sha256 "18aa0b2f8ff4d1bed229da68e457db482760c2a203bc8a36409ff731f6e4cbf3"

      def install
        bin.install "numary"
      end
    end
  end

  test do
    system "#{bin}/numary version"
  end
end
