# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Payments < Formula
  desc ""
  homepage "https://formance.com"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/payments/releases/download/v0.5.0/payments_darwin-amd64.tar.gz"
      sha256 "eba368f70858f9159bafc03bb141b769d776ec30d25edd0e2f41a05a500d59d2"

      def install
        bin.install "payments"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/formancehq/payments/releases/download/v0.5.0/payments_darwin-arm64.tar.gz"
      sha256 "afc45e0a63d7cbc913d9a1d870539ee99ead7dda966d053a396b86d8c23f2899"

      def install
        bin.install "payments"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/formancehq/payments/releases/download/v0.5.0/payments_linux-arm64.tar.gz"
      sha256 "8e8088b7afacd6be95da1cb590d1189f3a2d7ab8e532e9b2074c690aed110111"

      def install
        bin.install "payments"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/formancehq/payments/releases/download/v0.5.0/payments_linux-amd64.tar.gz"
      sha256 "0ced33d629c8da05c40bdfb394a5cb257c70adfdac13908f1061e96a35937449"

      def install
        bin.install "payments"
      end
    end
  end

  test do
    system "#{bin}/payments version"
  end
end
